format_version: 3
pipelines:
  docker-inception-dojo:
    group: dojo
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - "**/*.md"
    secure_variables:
      VAULT_TOKEN: "AES:OaFjqXGVuvsZuaqD2Wh31g==:sKIyeHDkexxOmPMS9WQZaAWhflSbC0Q0QsGgcFgqMN4="
    stages:
      - build:
          clean_workspace: true
          jobs:
            alpine-dind:
              resources:
                - docker
              artifacts:
                - build:
                    source: image/*imagerc
                    destination:
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks build alpine-dind
            ubuntu18-dind:
              resources:
                - docker
              artifacts:
                - build:
                    source: image/*imagerc
                    destination:
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks build ubuntu18-dind
      - itest:
          clean_workspace: true
          jobs:
            alpine-dind:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: alpine-dind
                    is_file: yes
                    source: alpine-dind.imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest alpine-dind
            ubuntu18-dind:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: ubuntu18-dind
                    is_file: yes
                    source: ubuntu18-dind.imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest ubuntu18-dind
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            alpine-dind:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: alpine-dind
                    is_file: yes
                    source: alpine-dind.imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish alpine-dind
            ubuntu18-dind:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: ubuntu18-dind
                    is_file: yes
                    source: ubuntu18-dind.imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish ubuntu18-dind
